### ISSUE TITLE
How to use and import it

### ISSUE THREAD

**Issue by maheraldous** [bberak/react-native-game-engine-template#2]
Hello I use your react-native-game-engine and in my game I want to use controller like this [https://www.npmjs.com/package/react-native-game-pad](https://www.npmjs.com/package/react-native-game-pad) but the snack can't load the "react-native-game-pad" so I tried to look after something else and I found your react-native-game-engine-template which might work with controller but I don't know how to use it

I really want to use something like below

```
<RNGamePad
  onStart={this.handleOnStart}
  onEnd={this.handleOnEnd}
  onMove={this.handleOnMove}
  onDir={this.handleOnDir}
  onDirUp={this.handleOnDirUp}
  onDirDown={this.handleOnDirDown}
  onDirLeft={this.handleOnDirLeft}
  onDirRight={this.handleOnDirRight}
  onPlane={this.handleOnPlane}
  onPlaneUp={this.handleOnPlaneUp}
  onPlaneDown={this.handleOnPlaneDown}
  onPlaneLeft={this.handleOnPlaneLeft}
  onPlaneRight={this.handleOnPlaneRight}
  onLeftStart={this.handleLeftOnStart} // methods for handling dual joysticks START
  onLeftEnd={this.handleLeftOnEnd}
  onLeftMove={this.handleLeftOnMove}
  onLeftDir={this.handleLeftOnDir}
  onLeftDirUp={this.handleLeftOnDirUp}
  onLeftDirDown={this.handleLeftOnDirDown}
  onLeftDirLeft={this.handleLeftOnDirLeft}
  onLeftDirRight={this.handleLeftOnDirRight}
  onLeftPlane={this.handleLeftOnPlane}
  onLeftPlaneUp={this.handleLeftOnPlaneUp}
  onLeftPlaneDown={this.handleLeftOnPlaneDown}
  onLeftPlaneLeft={this.handleLeftOnPlaneLeft}
  onLeftPlaneRight={this.handleLeftOnPlaneRight}
  onRightStart={this.handleRightOnStart}
  onRightEnd={this.handleRightOnEnd}
  onRightMove={this.handleRightOnMove}
  onRightDir={this.handleRightOnDir}
  onRightDirUp={this.handleRightOnDirUp}
  onRightDirDown={this.handleRightOnDirDown}
  onRightDirLeft={this.handleRightOnDirLeft}
  onRightDirRight={this.handleRightOnDirRight}
  onRightPlane={this.handleRightOnPlane}
  onRightPlaneUp={this.handleRightOnPlaneUp}
  onRightPlaneDown={this.handleRightOnPlaneDown}
  onRightPlaneLeft={this.handleRightOnPlaneLeft}
  onRightPlaneRight={this.handleRightOnPlaneRight}
  onButtonAPress={this.handleButtonAPress}
  onButtonAPress={this.handleButtonAPress}
  buttonAColor='red'
  onButtonBPress={this.handleButtonBPress}
  buttonBColor='green'
  dualJoystick={true}
  options={{
    size: 400,
    color: "blue",
    lockX: true
  }}
  options2={{
    size: 400,
    color: "red",
    lockY: true
  }}
/>
```

**Comment by bberak** [comment]
Hi @maheraldous,

The template uses a much simpler gamepad controller system that you can adapt to your needs: https://github.com/bberak/react-native-game-engine-template/blob/master/src/game/systems/gamepad-controller.js

The UI for the controller can also be adapted to your requirements: https://github.com/bberak/react-native-game-engine-template/blob/master/src/game/components/hud.js

That said, if you would like to use `RNGamePad` (which looks like a cool project), I would try to add the `RNGamePad` to your app tree, maybe just beside (as a sibling), above (as a parent) or below (as a child) of the `GameEngine` component. You can then funnel the events of the `RNGamePad` into your `GameEngine` using the `dispatch` api. I've left an untested snippet below:

```javascript
import React from "react";
import { GameEngine } from "react-native-game-engine";
import RNGamePad from "RNGamePad";
import ControllerSystem  from "./controllerSystem";
import HUD from "./hud";

class Game extends React.Component {

  handleGestures = (event) => {
    this.refs.gameEngine.dispatch({ type: "gesture", event })
  }   

  render() {
    return (
      <RNGamePad
        onStart={this.handleGestures}
        onEnd={this.handleGestures}
        onMove={this.handleGestures}
        onDir={this.handleGestures}
        onDirUp={this.handleGestures}
        onDirDown={this.handleGestures}
        onDirLeft={this.handleGestures}
        ...              
      >
        <GameEngine
          ref={"gameEngine"}
          systems={[ControllerSystem]}
          entities={{ hud: HUD()  }}
        />
      </RNGamePad>
    );
  }
}

export default Game;
```

You can then handle the gestures from your systems:

```javascript
const ControllerSystem = (entities, { events }) => {
    if (events.length) {
      //-- Do something with the events
      console.log(events);
   }
  
   return entities;
}
```

Hope that helps!

**Comment by maheraldous** [comment]
As I said "the snack can't load the "react-native-game-pad"" so I want to use your gamepad but I want a start push with an simple example in snack if you can. Because How to Start in ReadMe Dose not really explain to me. But I really Thank you for your replay :).
I am just bulding a test game in snack and you can see it here https://snack.expo.io/@maher-aldous/matter-game-v1

Currently I use the "react-native-swipe-gestures" but it dose not have the UpLeft, UpRight, DownLeft, DownRight.

**Comment by bberak** [comment]
Hi @maheraldous,

If you are building a simple game, then the `react-native-game-engine-template` repo is probably not right for you - it uses a 3D renderer instead of the default View-based renderer.

That said, a quick guide to get started using `react-native-game-engine` would be to take a look at the examples in the [Handbook](https://github.com/bberak/react-native-game-engine-handbook) project. This is an Expo-based project, so it should work with your current workflow. Also, have a read of the README [here](https://github.com/bberak/react-native-game-engine) - that is the core game engine project and will form the backbone of your game.

To get started with a vanilla project and import the game controller system you would:

1. Install `react-native-game-engine` to your project
2. Use the `GameEngine` component
3. Copy the [gamepad-controller](https://github.com/bberak/react-native-game-engine-template/blob/master/src/game/systems/gamepad-controller.js) system and integrate it into your systems similar to the code above. 
4. Copy the [HUD](https://github.com/bberak/react-native-game-engine-template/blob/master/src/game/components/hud.js) component and add it to your entities. I've modified the code above to explain this.

Hope that helps!

**Comment by maheraldous** [comment]
Thank you so much. I just wanted the game pad to controll the 2D box's movement, but I found in your `react-native-game-engine` project the answer which can be done like you did in the `single-touch`.

I used this code below in the `systems={[Physics]}` and it worked so I am closing the issue.

```
  let move = touches.find(x => x.type === "move");
  if (move) {
    Matter.Body.translate( entities['box'].body, {x: move.delta.pageX, y: move.delta.pageY});
  }
```

Just another question if you can answer it Mr. @bberak: What is the difference between `GameLoop` and `GameEngine`?

**Comment by bberak** [comment]
Nice find @maheraldous  - glad it helped :)

The `GameLoop` component is much simpler than the `GameEngine` in that it simply gives you an `onUpdate` callback with some parameters like touches, screen and time. I personally find it useful for simple scenes and interactions. 

The `GameEngine` is similar to the `GameLoop` but is a lot more opinionated in how you need to manage and structure your state using entities and systems (component-entity-systems architecture). I find it useful for more complex scenes, games and interactions. This is the component that I generally use (to be honest). 

I think I've documented a few more details here:

- https://github.com/bberak/react-native-game-engine#using-the-gameloop-component
- https://github.com/bberak/react-native-game-engine#managing-complexity-with-component-entity-systems
- https://github.com/bberak/react-native-game-engine#using-the-gameengine-component

Let me know if you need more info!

**Comment by maheraldous** [comment]
Thank you it's awesome :)

What do you say about making showcase in your project to let other people like me, submit their game's link from snack?

I think it will give more options to these who want to start than just having to go through the `react-native-game-engine`. We can share snack links also, to make it easier to test the demo.

**Comment by bberak** [comment]
No worries @maheraldous!

Yes, I'd be more than happy to publish links to snacks and showcase apps! That's what I was hoping to do with https://github.com/bberak/react-native-game-engine-handbook - but I haven't found time to keep adding content. So yeah, I think that's a great idea :)

**Comment by maheraldous** [comment]
No, you don't have to my friend. I meant let's make others share their snacks like I will do. I am almost done with my simple game and I can share my snack too. I will let you know when I am done. I am not professional like you but I did my best in this simple test game. I made it to know how to setup the most important things.

**Comment by bberak** [comment]
Cheers @maheraldous

**Comment by maheraldous** [comment]
Cheers @bberak  :)

**Comment by maheraldous** [comment]
@bberak Hello Again

I wonder why we can't use the matter-js as it used in the docs like this

```
Bodies.rectangle(400, 350, 720, 20, { 
render: {
  fillStyle: color, // use this when we want to color but this don't work when using it with react native
  strokeStyle: color,
  lineWidth: 1
}
});
```

In react native we do so

```
import React, { Component } from 'react';
import { View, Image } from 'react-native';
import { array, object, string } from 'prop-types';

export default class Ship extends Component {
  render() {
    const width = this.props.size[0];
    const height = this.props.size[1];
    const x = this.props.body.position.x - width / 2;
    const y = this.props.body.position.y - height / 2;
    
    return (
      <View
        style={{
          position: 'absolute',
          left: x,
          top: y,
          width: width,
          height: height,
          backgroundColor: this.props.color || 'pink',
        }}
      />
    );
  }
}

Ship.propTypes = {
    size: array,
    body: object, 
    color: string
}
```
Then in App.js `Import Ship`

```
// In App.js
const SHIP_WIDTH = 200;
const SHIP_HEIGHT = 100;

class game ... {
setupWorld = () => {
...
      const shipForm= Matter.Bodies.rectangle(100, 200, SHIP_WIDTH , SHIP_HEIGHT , {
        label: 'ship',
        friction: 1,
        restitution: 0,
      });
...
      const entities = {
        physics: { engine: engine, world: world },
        ship: { body: shipForm, size: [SHIP_WIDTH, SHIP_HEIGHT], color: 'blue', renderer: Ship},
// why no just put the color when we create the shipForm, instead of doing like above in the color = blue.
      };

}
}
```

This method is good so far with some boxes and basic shapes like circles but what if I want to draw something like this https://brm.io/matter-js/demo/#concave

I found out how to draw a star and the other objects are interacting with star when they colision but I can just see the square form of the star not the star itself because View compenent that I used, can't be a star form. With other words the star is there but some of the parts are not colored to be able to see it.

That's why I wonder if there is a way to use the

```
render: {
  fillStyle: color, // use this when we want to color but this don't work when using it with react native
  strokeStyle: color,
  lineWidth: 1
}
```

**Comment by bberak** [comment]
Hey @maheraldous,

I believe MatterJS ships with its own simple browser-based renderer which is utilized when you create bodies using the style below:

```javascript
Bodies.rectangle(400, 350, 720, 20, { 
render: {
  fillStyle: color, // use this when we want to color but this don't work when using it with react native
  strokeStyle: color,
  lineWidth: 1
}
});
```

However, because this is a browser-based renderer, it will not work with React Native. Although React Native appears to mimic a browser DOM, the backend implementation is completely different. This is why many browser-based NPM packages will also not work with React Native.

If you want to draw complex shapes (stars) with React Native, you'll probably need to use an external package like `React Native ART` or `React Native SVG` (or maybe use images).

Hope that helps!

**Comment by maheraldous** [comment]
Thanks I am trying to found out a way to draw the star with `React Native SVG` and I did but I don't know how to make it move with x and y like we do in the `View`

```
export default class Ship extends Component {
  render() {
    const width = this.props.size[0];
    const height = this.props.size[1];
    const x = this.props.body.position.x - width / 2;
    const y = this.props.body.position.y - height / 2;
    
    return (
      <View
        style={{
          position: 'absolute',
          left: x, // This is x
          top: y, // This is y
          width: width,
          height: height,
          backgroundColor: this.props.color || 'pink',
        }}
      />
    );
  }
}
```

**Comment by maheraldous** [comment]
Hi @bberak 
I solved the issue.

Another thing is in the dir `app/physics/rigid-bodies/systems.js`
I used this script
```
const CleanBoxes = (state, { touches, screen }) => {
	let world = state["physics"].world;

	Object.keys(state)
		.filter(key => state[key].body && state[key].body.position.y > screen.height * 2)
		.forEach(key => {
			Matter.Composite.remove(world, state[key].body);
			delete state[key];
		});

	return state;
};

export { Physics, CreateBox, MoveBox, CleanBoxes };
```
But the game stop when I removed an object but after some work and edit I was able to solve the stop issue, so if you have the same stop game issue please tell me so that I share the fix code with you.
